###
GET http://localhost:5000/api/compagnie


###
GET http://localhost:5000/api/compagnie/4


###
POST http://localhost:5000/api/compagnie
Content-Type: application/json

{
    "nom_compagnie": "EUROPA4"
}

###
PUT http://localhost:5000/api/compagnie/4
Content-Type: application/json


{
    "nom_compagnie": "88"
}

###
DELETE http://localhost:5000/api/compagnie/6
