###
GET http://localhost:5000/api/escale


###
GET http://localhost:5000/api/escale/19


###
POST http://localhost:5000/api/escale
Content-Type: application/json

{
    "date_arrive_navire": "2022-02-13",
    "date_depart_navire": "2023-02-13",
    "date_debut_operation": "2024-02-13",
    "date_fin_operation": "2025-02-13",
    "navire_id": 1
}

###
PUT http://localhost:5000/api/escale/2
Content-Type: application/json


{
    "date_arrive_navire": "2020-02-10",
    "date_depart_navire": "2020-02-10",
    "date_debut_operation": "2020-02-10",
    "date_fin_operation": "2020-02-10",
    "navire_id": 3
}

###
DELETE http://localhost:5000/api/escale/3
