###
GET http://localhost:5000/api/escale


###
GET http://localhost:5000/api/escale/19


###
POST http://localhost:5000/api/escale
Content-Type: application/json

{
    "date_arrive_navire": "2023-11-25",
    "date_depart_navire": "2023-11-27",
    "date_debut_operation": "2023-11-28",
    "date_fin_operation": "2023-11-28",
    "navire_id": 5
}

###
PUT http://localhost:5000/api/escale/8
Content-Type: application/json


{
    "date_arrive_navire": "2030-01-10",
    "date_depart_navire": "2030-05-18",
    "date_debut_operation": null,
    "date_fin_operation": null,
    "navire_id": 5
}

###
DELETE http://localhost:5000/api/escale/3
