###
GET http://localhost:5000/api/groupe_lieu


###
GET http://localhost:5000/api/groupe_lieu/4


###
POST http://localhost:5000/api/groupe_lieu
Content-Type: application/json

{
    "nom_groupe": "grp 4"
}

###
PUT http://localhost:5000/api/groupe_lieu/3
Content-Type: application/json


{
    "nom_groupe": "grp 3"
}

###
DELETE http://localhost:5000/api/groupe_lieu/4
