###
GET http://localhost:5000/api/parc


###
GET http://localhost:5000/api/parc/2


###
POST http://localhost:5000/api/parc
Content-Type: application/json

{
    "nom_parc": "parck 3"
}

###
PUT http://localhost:5000/api/parc/3
Content-Type: application/json


{
    "nom_parc": "88"
}

###
DELETE http://localhost:5000/api/parc/3
