###
GET http://localhost:5000/api/review


###
POST http://localhost:5000/api/review/shift_between_2_date
Content-Type: application/json

{
    "date_debut": "2022-11-07",
    "date_fin": "2023-11-09"
}

###
PUT http://localhost:5000/api/navire/7
Content-Type: application/json


{
    "nom_navire": "navire vaovao2"
}

###
DELETE http://localhost:5000/api/navire/6
